version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_IDENTIFIER: ${AUTH0_API_IDENTIFIER}
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
      VITE_AUTH0_API_IDENTIFIER: ${VITE_AUTH0_API_IDENTIFIER}
